### ISSUE TITLE
Initialization fails with new versions of Hashie gem (3.3.1)

### ISSUE THREAD

**Issue by calvinf** [americanbible/biblesearch-api-ruby#10]
Hi,

The latest version of the Hashie gem causes the BibleSearch class to fail to initialize.

My Gemfile:
```ruby
source "http://rubygems.org"
gem "biblesearch-api"
gem "hashie"
```

Gemfile.lock:
```ruby
GEM
  remote: http://rubygems.org/
  specs:
    biblesearch-api (1.1.0)
      hashie
      httparty
      oj
    hashie (3.3.1)
    httparty (0.13.1)
      json (~> 1.8)
      multi_xml (>= 0.5.2)
    json (1.8.1)
    multi_xml (0.5.5)
    oj (2.10.2)

PLATFORMS
  ruby

DEPENDENCIES
  biblesearch-api
  hashie
```

The error:
```bash
/Users/myuser/.rvm/gems/ruby-1.9.3-p448/gems/biblesearch-api-1.1.0/lib/biblesearch-api.rb:15:in `<top (required)>': uninitialized constant Hashie::HashExtensions (NameError)
	from /Users/myuser/.rvm/gems/ruby-1.9.3-p448/gems/bundler-1.7.2/lib/bundler/runtime.rb:76:in `require'
	from /Users/myuser/.rvm/gems/ruby-1.9.3-p448/gems/bundler-1.7.2/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /Users/myuser/.rvm/gems/ruby-1.9.3-p448/gems/bundler-1.7.2/lib/bundler/runtime.rb:72:in `each'
	from /Users/myuser/.rvm/gems/ruby-1.9.3-p448/gems/bundler-1.7.2/lib/bundler/runtime.rb:72:in `block in require'
	from /Users/myuser/.rvm/gems/ruby-1.9.3-p448/gems/bundler-1.7.2/lib/bundler/runtime.rb:61:in `each'
	from /Users/myuser/.rvm/gems/ruby-1.9.3-p448/gems/bundler-1.7.2/lib/bundler/runtime.rb:61:in `require'
	from /Users/myuser/.rvm/gems/ruby-1.9.3-p448/gems/bundler-1.7.2/lib/bundler.rb:133:in `require'
	from ./my-script.rb:6:in `<main>'
```

If I lock the Gemfile explicitly to Hashie gem 2.0.5 (the latest stable 2.0 release, and the one available at the time this gem was released), the BibleSearch class initializes successfully.

**Comment by natyconnor** [comment]
+100

I'm having to use calvinf's fork since the current state of the official gem is not working at all. Too many wrong dependencies everywhere. calvinf's works beautifully. Merge this pull request ASAP!

**Comment by bryceallison** [comment]
Thanks for the pull request calvinf. I've merged and published. Sorry for the delay on this everyone.

**Comment by angelacode** [comment]
I still seem to have the problem:

require 'biblesearch-api'
NameError: uninitialized constant Hashie::HashExtensions
    from /home/nitrous/code/kaya-nitrous/.bundle/gems/biblesearch-api-1.1.0/lib/biblesearch-api.rb:15:in `<top (required)>'
    from (irb):1:in`require'
    from (irb):1
    from /usr/local/opt/rbenv/versions/2.3.1/bin/irb:11:in `<main>'
